name: Continuos Integration

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
